version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./public/:/usr/src/app
            - ./.docker/nginx/api.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8888:80
        depends_on:
            - php
    db:
#        image: postgres
        image: postgis/postgis
        environment:
            POSTGRES_PASSWORD: example # Use postgres/example for user/password credentials
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/vendor
        env_file:
            - .env
        user: 1000:1000
